# First numpy

In [1]:
import numpy as np

In [4]:
a = np.random.randint(1,6,size=(10, 3))
a

array([[4, 4, 3],
       [3, 2, 2],
       [4, 1, 1],
       [4, 2, 2],
       [3, 1, 3],
       [4, 5, 1],
       [2, 3, 3],
       [3, 5, 2],
       [1, 2, 3],
       [5, 1, 3]])

In [12]:
double = a * 2
double

array([[ 8,  8,  6],
       [ 6,  4,  4],
       [ 8,  2,  2],
       [ 8,  4,  4],
       [ 6,  2,  6],
       [ 8, 10,  2],
       [ 4,  6,  6],
       [ 6, 10,  4],
       [ 2,  4,  6],
       [10,  2,  6]])

In [13]:
over3 = a > 3
over3

array([[ True,  True, False],
       [False, False, False],
       [ True, False, False],
       [ True, False, False],
       [False, False, False],
       [ True,  True, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False],
       [ True, False, False]])

In [14]:
a[over3]

array([4, 4, 4, 4, 4, 5, 5, 5])

# Pandas

In [15]:
import pandas as pd

In [25]:
df = pd.DataFrame(np.random.randint(1,10, size=(8,3)), columns=list('ABC'))
df

A  B  C
0  6  6  9
1  3  1  6
2  8  7  7
3  4  9  2
4  8  2  8
5  6  5  1
6  5  2  6
7  5  2  6

In [26]:
df['E'] = 'text'
df

A  B  C     E
0  6  6  9  text
1  3  1  6  text
2  8  7  7  text
3  4  9  2  text
4  8  2  8  text
5  6  5  1  text
6  5  2  6  text
7  5  2  6  text

In [27]:
df['F'] = np.random.randint(1,10,(8,3)).tolist()
df

A  B  C     E          F
0  6  6  9  text  [9, 6, 9]
1  3  1  6  text  [8, 5, 3]
2  8  7  7  text  [9, 9, 7]
3  4  9  2  text  [2, 7, 7]
4  8  2  8  text  [2, 1, 5]
5  6  5  1  text  [4, 1, 4]
6  5  2  6  text  [8, 4, 7]
7  5  2  6  text  [5, 1, 3]

In [29]:
over5 = df['A'] > 5
over5

0     True
1    False
2     True
3    False
4     True
5     True
6    False
7    False
Name: A, dtype: bool

In [30]:
df[over5]

A  B  C     E          F
0  6  6  9  text  [9, 6, 9]
2  8  7  7  text  [9, 9, 7]
4  8  2  8  text  [2, 1, 5]
5  6  5  1  text  [4, 1, 4]

In [31]:
df[ df['A'] > 5 ]

A  B  C     E          F
0  6  6  9  text  [9, 6, 9]
2  8  7  7  text  [9, 9, 7]
4  8  2  8  text  [2, 1, 5]
5  6  5  1  text  [4, 1, 4]

In [37]:
5 in df.F

True

In [39]:
df.F.apply(lambda x: 5 in x)

0    False
1     True
2    False
3    False
4     True
5    False
6    False
7     True
Name: F, dtype: bool

In [42]:
df[df['F'].apply(lambda x: 5 in x)]

A  B  C     E          F
1  3  1  6  text  [8, 5, 3]
4  8  2  8  text  [2, 1, 5]
7  5  2  6  text  [5, 1, 3]

In [49]:
df[df['F'].apply(lambda x: any(filter(lambda y: y > 5, x)))]

A  B  C     E          F
0  6  6  9  text  [9, 6, 9]
1  3  1  6  text  [8, 5, 3]
2  8  7  7  text  [9, 9, 7]
3  4  9  2  text  [2, 7, 7]
6  5  2  6  text  [8, 4, 7]