# First numpy

In [2]:
import numpy as np

In [3]:
a = np.random.randint(1,6,size=(10, 3))
a

array([[4, 2, 5],
       [1, 2, 4],
       [5, 1, 2],
       [3, 5, 1],
       [2, 3, 5],
       [1, 4, 2],
       [5, 2, 5],
       [2, 1, 4],
       [3, 4, 3],
       [2, 2, 2]])

In [4]:
double = a * 2
double

array([[ 8,  4, 10],
       [ 2,  4,  8],
       [10,  2,  4],
       [ 6, 10,  2],
       [ 4,  6, 10],
       [ 2,  8,  4],
       [10,  4, 10],
       [ 4,  2,  8],
       [ 6,  8,  6],
       [ 4,  4,  4]])

In [5]:
over3 = a > 3
over3

array([[ True, False,  True],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False, False,  True],
       [False,  True, False],
       [False, False, False]])

In [6]:
a[over3]

array([4, 5, 4, 5, 5, 5, 4, 5, 5, 4, 4])

# Pandas

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame(np.random.randint(1,10, size=(8,3)), columns=list('ABC'))
df

A  B  C
0  3  3  2
1  5  1  5
2  5  3  3
3  3  4  8
4  3  9  7
5  4  2  4
6  4  1  9
7  4  6  8

In [9]:
df['E'] = 'text'
df

A  B  C     E
0  3  3  2  text
1  5  1  5  text
2  5  3  3  text
3  3  4  8  text
4  3  9  7  text
5  4  2  4  text
6  4  1  9  text
7  4  6  8  text

In [10]:
df['F'] = np.random.randint(1,10,(8,3)).tolist()
df

A  B  C     E          F
0  3  3  2  text  [1, 6, 7]
1  5  1  5  text  [4, 4, 9]
2  5  3  3  text  [8, 1, 4]
3  3  4  8  text  [4, 5, 4]
4  3  9  7  text  [5, 4, 2]
5  4  2  4  text  [1, 6, 3]
6  4  1  9  text  [7, 5, 6]
7  4  6  8  text  [5, 1, 8]

In [14]:
over = df['A'] > 3
over

0    False
1     True
2     True
3    False
4    False
5     True
6     True
7     True
Name: A, dtype: bool

In [15]:
df[over]

A  B  C     E          F
1  5  1  5  text  [4, 4, 9]
2  5  3  3  text  [8, 1, 4]
5  4  2  4  text  [1, 6, 3]
6  4  1  9  text  [7, 5, 6]
7  4  6  8  text  [5, 1, 8]

In [18]:
df[ df['A'] > 3 ]

A  B  C     E          F
1  5  1  5  text  [4, 4, 9]
2  5  3  3  text  [8, 1, 4]
5  4  2  4  text  [1, 6, 3]
6  4  1  9  text  [7, 5, 6]
7  4  6  8  text  [5, 1, 8]

In [23]:
5 in df.F

True

In [24]:
df.F.apply(lambda x: 5 in x)

0    False
1    False
2    False
3     True
4     True
5    False
6     True
7     True
Name: F, dtype: bool

In [25]:
df[df['F'].apply(lambda x: 5 in x)]

A  B  C     E          F
3  3  4  8  text  [4, 5, 4]
4  3  9  7  text  [5, 4, 2]
6  4  1  9  text  [7, 5, 6]
7  4  6  8  text  [5, 1, 8]

In [26]:
df[df['F'].apply(lambda x: any(filter(lambda y: y > 5, x)))]

A  B  C     E          F
0  3  3  2  text  [1, 6, 7]
1  5  1  5  text  [4, 4, 9]
2  5  3  3  text  [8, 1, 4]
5  4  2  4  text  [1, 6, 3]
6  4  1  9  text  [7, 5, 6]
7  4  6  8  text  [5, 1, 8]

In [27]:
df.describe()

A         B        C
count  8.000000  8.000000  8.00000
mean   3.875000  3.625000  5.75000
std    0.834523  2.722263  2.60494
min    3.000000  1.000000  2.00000
25%    3.000000  1.750000  3.75000
50%    4.000000  3.000000  6.00000
75%    4.250000  4.500000  8.00000
max    5.000000  9.000000  9.00000

# Files

In [ ]:
# read, readline, readlines:
